ALTER PROCEDURE INSERT_CUSTOMER
	@CUST_CODE INT,
	@CUST_FNAME NVARCHAR(30),
	@CUST_LNAME NVARCHAR(30),
	@CUST_STREET NVARCHAR(50),
	@CUST_CITY NVARCHAR(30),
	@CUST_STATE NVARCHAR(30),
	@CUST_ZIP NVARCHAR(30),
	@CUST_BALANCE DECIMAL,
	@EMP_NUM INT,
	@EMP_FNAME VARCHAR(40),
	@EMP_LNAME VARCHAR(40),
	@EMP_EMAIL VARCHAR(40),
	@EMP_PHONE INT,
	@EMP_HIREDATE DATETIME,
	@EMP_TITLE VARCHAR(40),
	@EMP_COMM DECIMAL,
	@DEPT_NUM INT,
	@DEPT_NAME VARCHAR(30),
	@DEPT_MAILBOX VARCHAR(30),
	@DEPT_PHONE VARCHAR(30),
	@PROD_SKU VARCHAR(20),
	@PROD_DESCRIPTION VARCHAR(20),
	@PROD_TYPE VARCHAR(20),
	@PROD_BASE VARCHAR(20),
	@PROD_CATEGORY VARCHAR(20),
	@PROD_PRICE INT,
	@PROD_QOH INT,
	@PROD_MIN INT
	
	
AS 
BEGIN
INSERT INTO CUSTOMER_DIMENSION 
	(CUST_CODE,CUST_FNAME,CUST_LNAME,CUST_CITY,CUST_STATE,CUST_ZIP,CUST_BALANCE)
	VALUES(@CUST_CODE,@CUST_FNAME,@CUST_LNAME,@CUST_CITY,@CUST_STATE,@CUST_ZIP,@CUST_BALANCE)
END

BEGIN 
INSERT INTO EMPLOYEE_DIMENSION
(EMP_NUM,EMP_FNAME, EMP_LNAME,EMP_EMAIL,EMP_PHONE,EMP_HIREDATE ,EMP_TITLE ,EMP_COMM,DEPT_NUM) 
VALUES (@EMP_NUM,@EMP_FNAME, @EMP_LNAME,@EMP_EMAIL,@EMP_PHONE,@EMP_HIREDATE ,@EMP_TITLE ,@EMP_COMM,@DEPT_NUM)
END

BEGIN 
INSERT INTO DEPARTMENT_DIMENSION
(DEPT_NUM,DEPT_NAME,DEPT_MAILBOX,DEPT_PHONE)
VALUES(@DEPT_NUM,@DEPT_NAME,@DEPT_MAILBOX,@DEPT_PHONE)
END

BEGIN 
INSERT INTO PRODUCT_DIMENSION
(PROD_SKU,PROD_DESCRIPTION,PROD_TYPE,PROD_BASE,PROD_CATEGORY,PROD_PRICE,PROD_QOH,PROD_MIN)
VALUES(@PROD_SKU,@PROD_DESCRIPTION,@PROD_TYPE,@PROD_BASE,@PROD_CATEGORY,@PROD_PRICE,@PROD_QOH,@PROD_MIN)
END

TRUNCATE TABLE CUSTOMER_DIMENSION

INSERT INTO CUSTOMER_DIMENSION
(CUST_CODE,CUST_FNAME,CUST_LNAME,CUST_CITY,CUST_STATE,CUST_ZIP,CUST_BALANCE)
SELECT CUST_CODE,CUST_FNAME,CUST_LNAME,CUST_CITY,CUST_STATE,CUST_ZIP,CUST_BALANCE
FROM LGCUSTOMER 

SELECT *
FROM CUSTOMER_DIMENSION

TRUNCATE TABLE EMPLOYEE_DIMENSION

INSERT INTO EMPLOYEE_DIMENSION
(EMP_NUM,EMP_FNAME, EMP_LNAME,EMP_EMAIL,EMP_PHONE,EMP_HIREDATE ,EMP_TITLE ,EMP_COMM) 
SELECT EMP_NUM,EMP_FNAME, EMP_LNAME,EMP_EMAIL,EMP_PHONE,EMP_HIREDATE ,EMP_TITLE ,EMP_COMM
FROM LGEMPLOYEE

SELECT *
FROM EMPLOYEE_DIMENSION

TRUNCATE TABLE DEPARTMENT_DIMENSION

INSERT INTO DEPARTMENT_DIMENSION
(DEPT_NUM,DEPT_NAME,DEPT_MAILBOX,DEPT_PHONE)
SELECT DEPT_NUM,DEPT_NAME,DEPT_MAIL_BOX,DEPT_PHONE
FROM LGDEPARTMENT

SELECT *
FROM DEPARTMENT_DIMENSION

TRUNCATE TABLE PRODUCT_DIMENSION

INSERT INTO PRODUCT_DIMENSION
(PROD_SKU,PROD_DESCRIPTION,PROD_TYPE,PROD_BASE,PROD_CATEGORY,PROD_PRICE,PROD_QOH,PROD_MIN)
SELECT PROD_SKU,PROD_DESCRIPT,PROD_TYPE,PROD_BASE,PROD_CATEGORY,PROD_PRICE,PROD_QOH,PROD_MIN
FROM LGPRODUCT 

SELECT *
FROM PRODUCT_DIMENSION

TRUNCATE TABLE TIME_DIMENSION

INSERT INTO TIME_DIMENSION
(DATE,DAY,MONTH,YEAR)
SELECT INV_DATE,DATEPART(DAY,INV_DATE),DATEPART(MONTH,INV_DATE),DATEPART(YEAR,INV_DATE)
FROM LGINVOICE

SELECT *
FROM TIME_DIMENSION

TRUNCATE TABLE QUANTITY_FACT

INSERT INTO QUANTITY_FACT
(CUST_CODE,EMP_NUM,DEPT_NUM,PROD_SKU,DATE)
SELECT C.CUST_CODE, E.EMP_NUM,D.DEPT_NUM,P.PROD_SKU,T.DATE
FROM CUSTOMER_DIMENSION C,EMPLOYEE_DIMENSION E,DEPARTMENT_DIMENSION D, PRODUCT_DIMENSION P, TIME_DIMENSION T

TRUNCATE TABLE PRICE_FACT

INSERT INTO PRICE_FACT
(CUST_CODE,EMP_NUM,DEPT_NUM,PROD_SKU,DATE)
SELECT C.CUST_CODE, E.EMP_NUM,D.DEPT_NUM,P.PROD_SKU,T.DATE
FROM CUSTOMER_DIMENSION C,EMPLOYEE_DIMENSION E,DEPARTMENT_DIMENSION D, PRODUCT_DIMENSION P, TIME_DIMENSION T















