CREATE TABLE CUSTOMER_DIMENSION
(
CUST_CODE INT NOT NULL, 
CUST_FNAME NVARCHAR(30),
CUST_LNAME NVARCHAR(30),
CUST_STREET NVARCHAR(50),
CUST_CITY NVARCHAR(30),
CUST_STATE NVARCHAR(30),
CUST_ZIP NVARCHAR(30),
CUST_BALANCE DECIMAL
)

ALTER TABLE CUSTOMER_DIMENSION
ADD CONSTRAINT PK_CUSTOMER_DIMENSION PRIMARY KEY (CUST_CODE)

SELECT *
FROM CUSTOMER_DIMENSION
DROP TABLE CUSTOMER_DIMENSION

CREATE TABLE EMPLOYEE_DIMENSION
(
EMP_NUM INT NOT NULL,
EMP_FNAME NVARCHAR(40),
EMP_LNAME NVARCHAR(40),
EMP_EMAIL NVARCHAR(40),
EMP_PHONE NVARCHAR(10),
EMP_HIREDATE DATETIME,
EMP_TITLE NVARCHAR(40),
EMP_COMM DECIMAL,
DEPT_NUM INT
) 

ALTER TABLE EMPLOYEE_DIMENSION
ADD CONSTRAINT PK_EMPLOYEE_DIMENSION PRIMARY KEY (EMP_NUM)
ALTER TABLE EMPLOYEE_DIMENSION 
ADD CONSTRAINT FK_EMPLOYEE_DIMENSION FOREIGN KEY (DEPT_NUM) REFERENCES DEPARTMENT_DIMENSION(DEPT_NUM)

SELECT *
FROM EMPLOYEE_DIMENSION


CREATE TABLE DEPARTMENT_DIMENSION
(
DEPT_NUM INT NOT NULL,
DEPT_NAME VARCHAR(30),
DEPT_MAILBOX VARCHAR(30),
DEPT_PHONE VARCHAR(30), 
EMP_NUM INT
)

ALTER TABLE DEPARTMENT_DIMENSION
ADD CONSTRAINT PK_DEPARTMENT_DIMENSION PRIMARY KEY (DEPT_NUM)
ALTER TABLE DEPARTMENT_DIMENSION
ADD CONSTRAINT FK_DEPARTMENT_DIMENSION FOREIGN KEY (EMP_NUM) REFERENCES EMPLOYEE_DIMENSION (EMP_NUM)

SELECT * 
FROM DEPARTMENT_DIMENSION

CREATE TABLE PRODUCT_DIMENSION
(
PROD_SKU NVARCHAR(50) NOT NULL,
PROD_DESCRIPTION NVARCHAR(100),
PROD_TYPE NVARCHAR(50),
PROD_BASE NVARCHAR(50),
PROD_CATEGORY NVARCHAR(50),
PROD_PRICE DECIMAL,
PROD_QOH DECIMAL,
PROD_MIN DECIMAL
)

ALTER TABLE PRODUCT_DIMENSION
ADD CONSTRAINT PK_PRODUCT_DESCRIPTION PRIMARY KEY (PROD_SKU)
DROP TABLE PRODUCT_DIMENSION
SELECT * 
FROM PRODUCT_DIMENSION

CREATE TABLE TIME_DIMENSION
(
DATE DATE NOT NULL,
DAY INT,
MONTH INT,
YEAR INT 
)

ALTER TABLE TIME_DIMENSION
ADD CONSTRAINT PK_TIME_DIMENSION PRIMARY KEY (DATE) 


SELECT *
FROM TIME_DIMENSION

CREATE TABLE QUANTITY_FACT 
(
CUST_CODE INT NOT NULL, 
EMP_NUM INT NOT NULL,
DEPT_NUM INT NOT NULL, 
PROD_SKU NVARCHAR(50) NOT NULL,
DATE DATE NOT NULL, 
PROD_QOH INT
)

ALTER TABLE QUANTITY_FACT 
ADD CONSTRAINT PK_QUANTITY_FACT PRIMARY KEY (CUST_CODE,EMP_NUM,DEPT_NUM,PROD_SKU,DATE)
DROP TABLE QUANTITY_FACT


SELECT *
FROM QUANTITY_FACT


CREATE TABLE PRICE_FACT 
(
CUST_CODE INT NOT NULL,
EMP_NUM INT NOT NULL,
DEPT_NUM INT NOT NULL,
PROD_SKU VARCHAR(20) NOT NULL,
DATE DATE NOT NULL,
PROD_PRICE INT
)

ALTER TABLE PRICE_FACT 
ADD CONSTRAINT PK_PRICE_FACT PRIMARY KEY (CUST_CODE,EMP_NUM,DEPT_NUM,PROD_SKU,DATE)

SELECT *
FROM PRICE_FACT




