--A8
--Jordan Johnson
--CIS310
--DUE 11/9/15

--1
SELECT ItemID,Description,ListPrice
FROM cis310A8..Merchandise
WHERE ListPrice >= (SELECT AVG(LISTPRICE)
					FROM cis310A8..Merchandise
					) 

--2
SELECT O.ItemID,AVG(O.Cost)AS AVERAGECOST,AVG(S.SalePrice)AS AVERAGESALEPRICE
FROM cis310A8..OrderItem O INNER JOIN cis310A8..SaleItem S ON O.ItemID=S.ItemID
GROUP BY O.ItemID
HAVING AVG(S.SalePrice)>1.5*AVG(O.Cost)
ORDER BY AVERAGECOST,AVERAGESALEPRICE

--3
SELECT E.EmployeeID, E.LastName,SUM(I.Quantity*I.SalePrice)AS TOTALSALES,SUM(I.Quantity*I.SalePrice)/COUNT(I.SalePrice)AS PCTSALES
FROM cis310A8..Employee E INNER JOIN cis310A8..Sale S ON E.EmployeeID=S.EmployeeID INNER JOIN cis310A8..SaleItem I ON
I.SaleID=S.SaleID 
GROUP BY E.EmployeeID ,E.LastName
ORDER BY TOTALSALES,PCTSALES


--4
SELECT DISTINCT S.SupplierID,S.Name,SUM(O.Quantity*O.Cost)/SUM(M.ShippingCost) AS PCTSHIPCOST
FROM CIS310A8..Supplier S INNER JOIN cis310A8..MerchandiseOrder M ON S.SupplierID=M.SupplierID INNER JOIN cis310A8..OrderItem O ON 
M.PONumber=O.PONumber
GROUP BY S.SupplierID,S.Name
HAVING SUM(O.Quantity*O.Cost)/SUM(M.ShippingCost)= (SELECT MAX(TEMP.PCTSHIPCOST) AS LARGESTPCTCOST
													FROM (SELECT S.SupplierID,SUM(O.Quantity*O.Cost)/SUM(M.ShippingCost) AS PCTSHIPCOST
														  FROM CIS310A8..Supplier S INNER JOIN cis310A8..MerchandiseOrder M ON S.SupplierID=M.SupplierID 
														  INNER JOIN cis310A8..OrderItem O ON M.PONumber=O.PONumber
														  GROUP BY S.SupplierID)TEMP
														  )
ORDER BY PCTSHIPCOST

--5
SELECT C.CustomerID,C.LastName,C.FirstName,SUM(I.Quantity*I.SalePrice) AS MERCTOTAL,SUM(A.SALEPRICE) AS ANIMALTOTAL,SUM(I.Quantity*I.SalePrice)+SUM(A.SALEPRICE) AS GRANDTOTAL
FROM CIS310A8..Customer C INNER JOIN CIS310A8..Sale S ON C.CustomerID=S.CustomerID INNER JOIN cis310A8..SaleAnimal A
ON S.SaleID=A.SaleID INNER JOIN CIS310A8..SaleItem I ON S.SaleID=I.SaleID
GROUP BY C.CustomerID,C.LastName,C.FirstName
HAVING SUM(I.Quantity*I.SalePrice)+SUM(A.SALEPRICE)=(SELECT MAX(TEMP.GRANDTOTAL)AS LARGEGRANDTOTAL
													 FROM (SELECT C.CustomerID,SUM(I.Quantity*I.SalePrice)+SUM(A.SALEPRICE)AS GRANDTOTAL
														   FROM CIS310A8..Customer C INNER JOIN CIS310A8..Sale S ON C.CustomerID=S.CustomerID INNER JOIN cis310A8..SaleAnimal A
														   ON S.SaleID=A.SaleID INNER JOIN CIS310A8..SaleItem I ON S.SaleID=I.SaleID
														   GROUP BY C.CustomerID)TEMP
														   )
ORDER BY MERCTOTAL,ANIMALTOTAL,GRANDTOTAL


--6
SELECT C.CustomerID,C.LastName,C.FirstName,SUM(I.SalePrice)AS MAYTOTAL
FROM  CIS310A8..Customer C INNER JOIN CIS310A8..Sale S ON C.CustomerID=S.CustomerID INNER JOIN cis310A8..SaleAnimal A
ON S.SaleID=A.SaleID INNER JOIN CIS310A8..SaleItem I ON S.SaleID=I.SaleID
WHERE SaleDate>'2004-05-01' AND SaleDate < '2004-05-31' AND I.SalePrice > 100
GROUP BY  C.CustomerID,C.LastName,C.FirstName
ORDER BY MAYTOTAL

--7
SELECT M.Description, M.ItemID,SUM(M.QuantityOnHand) AS PURCHASED, SUM(I.Quantity)AS SOLD,SUM(M.QuantityOnHand-I.Quantity)AS NETINCREASE
FROM cis310A8..Merchandise M INNER JOIN cis310A8..SaleItem I ON M.ItemID=I.ItemID INNER JOIN CIS310A8..Sale S ON I.SaleID=S.SaleID
WHERE S.SaleDate>'2004-01-01' AND S.SaleDate < '2004-07-31' AND M.Description='DOG FOOD-CAN-PREMIUM'
GROUP BY  M.Description, M.ItemID
ORDER BY PURCHASED,SOLD,NETINCREASE

--8
SELECT M.ItemID,M.Description,M.ListPrice
FROM cis310A8..Merchandise M RIGHT OUTER JOIN cis310A8..SaleItem I ON M.ItemID=I.ItemID INNER JOIN CIS310A8..Sale S ON I.SaleID=S.SaleID
WHERE S.SaleDate>'2004-07-01' AND S.SaleDate < '2004-07-31' AND M.ListPrice>50 

--9
SELECT M.ItemID,M.Description,M.QuantityOnHand,I.ItemID
FROM cis310A8..Merchandise M FULL OUTER JOIN cis310A8..SaleItem I ON M.ItemID=I.ItemID FULL OUTER JOIN CIS310A8..Sale S ON I.SaleID=S.SaleID
WHERE S.SaleDate>'2004-12-31' OR S.SaleDate < '2004-01-01' OR S.SaleDatE IS NULL AND M.QuantityOnHand>100

--10
SELECT M.ItemID,M.Description,M.QuantityOnHand,I.ItemID
FROM cis310A8..Merchandise M FULL OUTER JOIN cis310A8..SaleItem I ON M.ItemID=I.ItemID FULL OUTER JOIN CIS310A8..Sale S ON I.SaleID=S.SaleID
WHERE S.SaleDate IN (SELECT SaleDate
				     FROM cis310A8..Merchandise M FULL OUTER JOIN cis310A8..SaleItem I ON M.ItemID=I.ItemID FULL OUTER JOIN CIS310A8..Sale S ON I.SaleID=S.SaleID
					 WHERE SaleDate>'2004-12-31' OR SaleDate < '2004-01-01' OR SaleDate IS NULL
					 )  
                     AND M.QuantityOnHand>100

--11
SELECT C.CustomerID,C.LastName,C.FirstName,SUM(I.Quantity*I.SalePrice) AS MERCTOTAL,SUM(A.SALEPRICE) AS ANIMALTOTAL,SUM(I.Quantity*I.SalePrice)+SUM(A.SALEPRICE) AS GRANDTOTAL
FROM CIS310A8..Customer C INNER JOIN CIS310A8..Sale S ON C.CustomerID=S.CustomerID INNER JOIN cis310A8..SaleAnimal A
ON S.SaleID=A.SaleID INNER JOIN CIS310A8..SaleItem I ON S.SaleID=I.SaleID,CIS310A8..Category
GROUP BY C.CustomerID,C.LastName,C.FirstName
ORDER BY MERCTOTAL,ANIMALTOTAL,GRANDTOTAL

CREATE TABLE CATEGORY 
(
CATEGORY_NAME VARCHAR(50) NOT NULL,
CATEGORY_LOW INT,
CATEGORY_HIGH INT 
PRIMARY KEY(CATEGORY_NAME)
)
INSERT INTO CATEGORY(CATEGORY_NAME,CATEGORY_LOW,CATEGORY_HIGH)
VALUES('WEAK',0,200)
INSERT INTO CATEGORY(CATEGORY_NAME,CATEGORY_LOW,CATEGORY_HIGH)
VALUES('GOOD',200,800)
INSERT INTO CATEGORY(CATEGORY_NAME,CATEGORY_LOW,CATEGORY_HIGH)
VALUES('BEST',800,1000)

SELECT C.CustomerID,C.LastName,C.FirstName,SUM(I.Quantity*I.SalePrice) AS MERCTOTAL,SUM(A.SALEPRICE) AS ANIMALTOTAL,SUM(I.Quantity*I.SalePrice)+SUM(A.SALEPRICE) AS GRANDTOTAL,CATEGORY_NAME
FROM CIS310A8..Customer C INNER JOIN CIS310A8..Sale S ON C.CustomerID=S.CustomerID INNER JOIN cis310A8..SaleAnimal A
ON S.SaleID=A.SaleID INNER JOIN CIS310A8..SaleItem I ON S.SaleID=I.SaleID,CATEGORY
GROUP BY C.CustomerID,C.LastName,C.FirstName,CATEGORY_NAME
ORDER BY MERCTOTAL,ANIMALTOTAL,GRANDTOTAL

--12
SELECT S.Name
FROM CIS310A8..Supplier S INNER JOIN CIS310A8..AnimalOrder A ON S.SupplierID=A.SupplierID INNER JOIN cis310A8..MerchandiseOrder M ON 
S.SupplierID=M.SupplierID
WHERE M.OrderDate>'2004-06-01' AND M.OrderDate<'2004-06-31' AND A.OrderDate>'2004-06-01' AND A.OrderDate<'2004-06-31'
GROUP BY S.Name


--13
UPDATE CATEGORY
SET CATEGORY_HIGH=400


--15
DELETE FROM CATEGORY
WHERE CATEGORY_NAME='WEAK' AND CATEGORY_LOW=0 AND CATEGORY_HIGH=400

--14
DROP TABLE CATEGORY

--16




	

				
