--Jordan Johnson 
--CIS310-01
--A9
--Due 11/30/15
CREATE TRIGGER A9TRIGGER ON ORDER_LINE
AFTER INSERT
AS 
BEGIN
	DECLARE @NUM_ORDERED INT
	DECLARE	@ITEM_NUM CHAR(4)

	SELECT	*
	FROM	INSERTED

	SELECT	@ITEM_NUM = ITEM_NUM,
			@NUM_ORDERED = NUM_ORDERED
	FROM	INSERTED

	UPDATE	ITEM
	SET		ON_HAND = ON_HAND - @NUM_ORDERED
	WHERE	ITEM_NUM = @ITEM_NUM
END
BEGIN
	
	SELECT	*
	FROM	DELETED

	SELECT	@ITEM_NUM = ITEM_NUM,
			@NUM_ORDERED = NUM_ORDERED
	FROM	DELETED

	UPDATE	ITEM
	SET		ON_HAND = ON_HAND + @NUM_ORDERED
	WHERE	ITEM_NUM = @ITEM_NUM
END


--Test Trigger 

SELECT *
FROM ORDER_LINE

UPDATE ORDER_LINE
SET NUM_ORDERED=NUM_ORDERED+25
WHERE ORDER_NUM='51617' AND ITEM_NUM='NL89'

UPDATE ORDER_LINE
SET NUM_ORDERED=NUM_ORDERED-25
WHERE ORDER_NUM='51623' AND ITEM_NUM='FH24'


