select *
from CIS310A8..ANIMAL

--OUTER JOINS
SELECT *
FROM REP 

SELECT DISTINCT REP_NUM 
FROM CUSTOMER

SELECT *
FROM REP R INNER JOIN CUSTOMER C ON R.REP_NUM=C.REP_NUM
--LISTS ALL REPS AND THEIR CUSTOMERS EVEN IF A REP DOES NOT HAVE ANY CUSTOMER 
SELECT * 
FROM REP R LEFT OUTER JOIN CUSTOMER C ON R.REP_NUM=C.REP_NUM
ORDER BY R.REP_NUM

SELECT * 
FROM CUSTOMER C RIGHT OUTER JOIN REP R ON R.REP_NUM=C.REP_NUM
ORDER BY R.REP_NUM

SELECT *
FROM ITEM 
WHERE ITEM_NUM NOT IN(SELECT ITEM_NUM
					  FROM ITEM 
					  ORDER_LINE)
--SHOULD EXPECT INNER JOIN AND OUTER JOIN TO RETURN THE SAME RESULTS 
--FULL OUTER JOIN 
SELECT *
FROM CUSTOMER 

UPDATE CUSTOMER 
SET REP_NUM=NULL
WHERE CUSTOMER_NUM =893


SELECT * 
FROM CUSTOMER C FULL OUTER JOIN REP R ON R.REP_NUM=C.REP_NUM
ORDER BY R.REP_NUM
					 

--VIEWS 
--FIND THE CITY NAME THAT HAS THE HIGHETS CUSTOMER AVERAGE CUSTOMER CREDIT LIMIT 
CREATE VIEW AVG_CUSTOMER_CREDIT_LIMIT AS 
SELECT CITY, AVG(CREDIT_LIMIT) AS AVG_LIMIT 
FROM CUSTOMER 
GROUP BY CITY 

SELECT CITY 
FROM AVG_CUSTOMER_CREDIT_LIMIT 
WHERE AVG_LIMIT=
(SELECT MAX(AVG_LIMIT) 
 FROM AVG_CUSTOMER_CREDIT_LIMIT)
 
 CREATE TABLE REP
 (
	REP_NUM INT NOT NULL, LAST_NAME VARCHAR(50),
 )	

 ALTER TABLE REP
 ADD CONSTRAINT PK_REP PRIMARY KEY(REP_NUM)

  ALTER TABLE REP
 ADD CONSTRAINT FK_CUSTOMER_REP FOREIGN KEY(REP_NUM),REFERENCES REP
