SELECT *
FROM ORDER_LINE

SELECT ITEM_NUM, COUNT(*)
FROM ORDER_LINE
GROUP BY ITEM_NUM

SELECT ITEM_NUM, ON_HAND 
FROM ITEM 
WHERE ITEM_NUM IN ('FD11','KL78','TR40')

UPDATE ORDER_LINE
SET NUM_ORDERED=NUM_ORDERED +10
WHERE ORDER_NUM= 51610 OR ITEM_NUM='FD11'