EXEC INSERTITEM 'XY99','LYDIA','FOO',10

SELECT *
FROM ITEM
ORDER BY ITEM_NUM DESC

CREATE TABLE TEST 
(
	ID INT IDENTITY, 
	NAME VARCHAR(30)
)
ALTER TABLE TEST 
ADD CONSTRAINT PK_TEST PRIMARY KEY(ID)

INSERT INTO TEST
VALUES('A')

SELECT *
FROM TEST

--USE TRUNCATE
TRUNCATE TABLE TEST 
--MUST DISABLE OR REMOVE FK CONSTRAINTS BEFORE TRUNCATE CAN BE USED 

--DO NOT RECOMMEND DELETE

ALTER TABLE TEST 
NOCHECK CONSTRAINT PK_TEST

---FOR ASSIGNMENT 10
DISABLE FK CONSTRAINTS
TRUNCATE TABLES
ENABLE FK CONSTRAINTS 
POPULATE DIMENSION TABLES  