SELECT	*
FROM	CIS310A8..ANIMAL
--OUTER JOINS
SELECT	*
FROM	REP

SELECT	DISTINCT REP_NUM
FROM	CUSTOMER

SELECT	*
FROM	REP R INNER JOIN CUSTOMER C ON
		R.REP_NUM = C.REP_NUM
--LIST ALL REPS AND THEIR CUSTOMERS EVEN
--IF A REP DOES NOT HAVE ANY CUSTOMER
SELECT	*
FROM	REP R LEFT OUTER JOIN CUSTOMER C ON
		R.REP_NUM = C.REP_NUM
ORDER BY R.REP_NUM

SELECT	*
FROM	CUSTOMER C RIGHT OUTER JOIN REP R ON
		R.REP_NUM = C.REP_NUM
ORDER BY R.REP_NUM

SELECT	*
FROM	ITEM
WHERE	ITEM_NUM NOT IN
		(SELECT	ITEM_NUM
		 FROM	ITEM
		 ORDER_LINE)
--SHOUDL EXPECT INNER JOIN AND OUTER JOIN TO RETURN
--THE SAME RESULTS
--FULL OUTER JOIN
SELECT	*
FROM	CUSTOMER

UPDATE	CUSTOMER
SET		REP_NUM = NULL
WHERE	CUSTOMER_NUM = 893

SELECT	*
FROM	CUSTOMER C FULL OUTER JOIN REP R ON
		R.REP_NUM = C.REP_NUM
ORDER BY R.REP_NUM

--VIEWS
--FIND THE CITY NAME THAT HAS THE HIGHEST  
--AVERAGE CUSTOMER CREDIT LIMIT

CREATE VIEW AVG_CUSTOMER_CREDIT_LIMIT AS
SELECT	CITY, AVG(CREDIT_LIMIT) AS AVG_LIMIT
FROM	CUSTOMER
GROUP BY CITY

SELECT	CITY
FROM	AVG_CUSTOMER_CREDIT_LIMIT
WHERE	AVG_LIMIT = 
		(SELECT	MAX(AVG_LIMIT)
		 FROM	AVG_CUSTOMER_CREDIT_LIMIT
		)

DROP TABLE ORDER_LINE
DROP TABLE ORDERS
DROP TABLE CUSTOMER
DROP TABLE REP
DROP TABLE ITEM

CREATE TABLE REP
(
	REP_NUM INT NOT NULL,
	LAST_NAME VARCHAR(50)
)

CREATE	TABLE CUSTOMER
(
	CUSTOMER_NUM INT NOT NULL,
	CUSTOMER_NAME VARCHAR(50),
	REP_NUM INT
)

CREATE TABLE ORDERS
(
	ORDER_NUM INT NOT NULL,
	CUSTOMER_NUM INT
)

CREATE TABLE ORDER_LINE
(
	ITEM_NUM INT NOT NULL,
	ORDER_NUM INT NOT NULL
)

CREATE TABLE ITEM
(
	ITEM_NUM INT NOT NULL,
	DESCRIPTION VARCHAR(50)
)

ALTER TABLE REP
ADD CONSTRAINT PK_REP PRIMARY KEY(REP_NUM)

ALTER TABLE CUSTOMER
ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY(CUSTOMER_NUM)

ALTER TABLE ORDERS
ADD CONSTRAINT PK_ORDERS PRIMARY KEY(ORDER_NUM)

ALTER TABLE ITEM
ADD CONSTRAINT PK_ITEM PRIMARY KEY(ITEM_NUM)

ALTER TABLE ORDER_LINE
ADD CONSTRAINT PK_ORDER_LINE PRIMARY KEY(ITEM_NUM, ORDER_NUM)

ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_REP FOREIGN KEY(REP_NUM) REFERENCES REP

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY(CUSTOMER_NUM) REFERENCES CUSTOMER

ALTER TABLE ORDER_LINE
ADD	CONSTRAINT FK_ORDER_LINE_ORDERS FOREIGN KEY(ORDER_NUM) REFERENCES ORDERS,
	CONSTRAINT FK_ORDER_LINE_ITEM FOREIGN KEY(ITEM_NUM) REFERENCES ITEM

