--INSERT STATEMENT
SELECT	*
FROM	REP

INSERT INTO REP
VALUES(666, 'CLINTON', 'HILLARY', NULL,
		NULL, 'NY', NULL, NULL, NULL)

UPDATE	REP
SET		REP_NUM = 66
WHERE	STATE = 'NY'

INSERT INTO REP
(REP_NUM, FIRST_NAME, LAST_NAME, STATE)
VALUES(77, 'BERNIE', 'SANDERS', 'VT')

UPDATE	CUSTOMER
SET		REP_NUM = 15
WHERE	REP_NUM IS NULL

--CREATE AND POPULATE AT THE SAME TIME
SELECT	*
INTO	REP_WITH_NO_CUSTOMER
FROM	REP
WHERE	REP_NUM NOT IN (SELECT	REP_NUM
						FROM	CUSTOMER
					   )

SELECT	*
FROM	REP_WITH_NO_CUSTOMER

DELETE
FROM	REP_WITH_NO_CUSTOMER


INSERT	INTO REP_WITH_NO_CUSTOMER
SELECT	*
FROM	REP
WHERE	REP_NUM NOT IN (SELECT	REP_NUM
						FROM	CUSTOMER
					   )

