--MULTI TABLE QUERIES
--1
SELECT	O.ORDER_NUM, O.ORDER_DATE,
		C.CUSTOMER_NAME
FROM	ORDERS O INNER JOIN CUSTOMER C
		ON O.CUSTOMER_NUM = C.CUSTOMER_NUM


--QUINCY'S QUESTION
SELECT	*
FROM	CUSTOMER, ORDERS
--THIS IS THE PRODUCT OF CUSTOMER AND ORDERS

--2
SELECT	O.ORDER_NUM, O.ORDER_DATE,
		C.CUSTOMER_NAME
FROM	ORDERS O INNER JOIN CUSTOMER C
		ON O.CUSTOMER_NUM = C.CUSTOMER_NUM
WHERE	O.ORDER_DATE = '2015-OCT-15'


--3
SELECT	O.ORDER_NUM, O.ORDER_DATE,
		L.ITEM_NUM, L.NUM_ORDERED
FROM	ORDERS O INNER JOIN ORDER_LINE L ON O.ORDER_NUM = L.ORDER_NUM

SELECT	*
FROM	ORDERS, ORDER_LINE

--4
SELECT	CUSTOMER_NAME, CUSTOMER_NUM
FROM	CUSTOMER
WHERE	CUSTOMER_NUM IN 
		(SELECT	DISTINCT CUSTOMER_NUM
		 FROM	ORDERS
		 WHERE	ORDER_DATE = '2015-OCT-15'
		)

--USING A JOIN 
SELECT	DISTINCT C.CUSTOMER_NAME, C.CUSTOMER_NUM
FROM	CUSTOMER C INNER JOIN ORDERS O ON C.CUSTOMER_NUM = O.CUSTOMER_NUM
WHERE	O.ORDER_DATE = '2015-OCT-15'

--

SELECT	*
FROM	ORDERS
WHERE	CUSTOMER_NUM = 586

SELECT	*
FROM	ORDERS, CUSTOMER
WHERE	CUSTOMER.CUSTOMER_NUM = 586

--5
SELECT	DISTINCT C.CUSTOMER_NAME, C.CUSTOMER_NUM
FROM	CUSTOMER C 
WHERE	EXISTS
		(
		 SELECT	*
		 FROM	ORDERS O
		 WHERE	O.CUSTOMER_NUM = C.CUSTOMER_NUM AND
				O.ORDER_DATE = '2015-OCT-15'
		)

SELECT	*
FROM	CUSTOMER

--6
SELECT	CUSTOMER_NAME, CUSTOMER_NUM
FROM	CUSTOMER
WHERE	CUSTOMER_NUM NOT IN 
		(SELECT	DISTINCT CUSTOMER_NUM
		 FROM	ORDERS
		 WHERE	ORDER_DATE = '2015-OCT-15'
		)

SELECT	DISTINCT C.CUSTOMER_NAME, C.CUSTOMER_NUM
FROM	CUSTOMER C 
WHERE	NOT EXISTS
		(
		 SELECT	*
		 FROM	ORDERS O
		 WHERE	O.CUSTOMER_NUM = C.CUSTOMER_NUM AND
				O.ORDER_DATE = '2015-OCT-15'
		)

--7
SELECT	O.ORDER_NUM, O.ORDER_DATE,
		I.ITEM_NUM, I.DESCRIPTION, I.CATEGORY
FROM	(ORDERS O INNER JOIN ORDER_LINE L ON O.ORDER_NUM = L.ORDER_NUM)
		INNER JOIN ITEM I ON I.ITEM_NUM = L.ITEM_NUM

--8
SELECT	O.ORDER_NUM, O.ORDER_DATE,
		I.ITEM_NUM, I.DESCRIPTION, I.CATEGORY
FROM	(ORDERS O INNER JOIN ORDER_LINE L ON O.ORDER_NUM = L.ORDER_NUM)
		INNER JOIN ITEM I ON I.ITEM_NUM = L.ITEM_NUM
ORDER BY I.CATEGORY, I.ITEM_NUM

--9
SELECT	*
FROM	REP
WHERE	REP_NUM IN 
		(
		 SELECT	REP_NUM
		 FROM	CUSTOMER
		 WHERE	CREDIT_LIMIT >= 10000
		)

--10
SELECT	*
FROM	REP R
WHERE	EXISTS
		(
		 SELECT	C.REP_NUM
		 FROM	CUSTOMER C
		 WHERE	CREDIT_LIMIT >= 10000 AND
				R.REP_NUM = C.REP_NUM
		)

SELECT	R.REP_NUM, R.LAST_NAME
FROM	REP R INNER JOIN CUSTOMER C ON R.REP_NUM = C.REP_NUM
WHERE	C.CREDIT_LIMIT >= 10000

--11
SELECT	C.CUSTOMER_NAME, I.DESCRIPTION
FROM	CUSTOMER C INNER JOIN ORDERS O ON C.CUSTOMER_NUM = O.CUSTOMER_NUM
		INNER JOIN ORDER_LINE L ON O.ORDER_NUM = L.ORDER_NUM
		INNER JOIN ITEM I ON L.ITEM_NUM = I.ITEM_NUM
WHERE	I.DESCRIPTION = 'ROCKING HORSE'

--12
SELECT	*
FROM	ITEM

SELECT	A.ITEM_NUM, A.CATEGORY, B.ITEM_NUM, B.CATEGORY
FROM	ITEM A INNER JOIN ITEM B ON A.CATEGORY = B.CATEGORY
WHERE	A.ITEM_NUM < B.ITEM_NUM

--

--13
SELECT	O.ORDER_NUM, O.ORDER_DATE
FROM	ORDERS O INNER JOIN CUSTOMER C ON O.CUSTOMER_NUM = C.CUSTOMER_NUM
WHERE	C.CUSTOMER_NAME LIKE '%JOHNSON''S DEPARTMENT%'

--14
SELECT	O.ORDER_NUM, O.ORDER_DATE
FROM	ORDERS O 
WHERE	O.ORDER_NUM IN (SELECT	ORDER_NUM 
						FROM	ORDER_LINE
						WHERE	ITEM_NUM IN (SELECT	ITEM_NUM
											 FROM	ITEM
											 WHERE	DESCRIPTION = 'FIRE ENGINE'
											)
						)

--15
SELECT	O.ORDER_NUM, O.ORDER_DATE
FROM	ORDERS O 
WHERE	O.ORDER_NUM IN (SELECT	ORDER_NUM 
						FROM	ORDER_LINE
						WHERE	ITEM_NUM IN (SELECT	ITEM_NUM
											 FROM	ITEM
											 WHERE	DESCRIPTION = 'FIRE ENGINE'
											)
						)
		OR
		O.CUSTOMER_NUM IN (SELECT	CUSTOMER_NUM
						   FROM		CUSTOMER
						   WHERE	CUSTOMER_NAME = 'ALMONDTON GENERAL STORE'
						  )

--16
SELECT	O.ORDER_NUM, O.ORDER_DATE
FROM	ORDERS O 
WHERE	O.ORDER_NUM IN (SELECT	ORDER_NUM 
						FROM	ORDER_LINE
						WHERE	ITEM_NUM IN (SELECT	ITEM_NUM
											 FROM	ITEM
											 WHERE	DESCRIPTION = 'FIRE ENGINE'
											)
						)
		AND
		O.CUSTOMER_NUM IN (SELECT	CUSTOMER_NUM
						   FROM		CUSTOMER
						   WHERE	CUSTOMER_NAME = 'ALMONDTON GENERAL STORE'
						  )		
--17
SELECT	O.ORDER_NUM, O.ORDER_DATE
FROM	ORDERS O 
WHERE	O.ORDER_NUM NOT IN (SELECT	ORDER_NUM 
						FROM	ORDER_LINE
						WHERE	ITEM_NUM IN (SELECT	ITEM_NUM
											 FROM	ITEM
											 WHERE	DESCRIPTION = 'FIRE ENGINE'
											)
						)
		AND
		O.CUSTOMER_NUM IN (SELECT	CUSTOMER_NUM
						   FROM		CUSTOMER
						   WHERE	CUSTOMER_NAME = 'ALMONDTON GENERAL STORE'
						  )		
--18
SELECT	*
FROM	ITEM
WHERE	PRICE > (SELECT MAX(PRICE) FROM ITEM WHERE CATEGORY = 'GME')	

SELECT	*
FROM	ITEM
WHERE	PRICE > ALL (SELECT PRICE FROM ITEM WHERE CATEGORY = 'GME')		

--20

SELECT	*
FROM	ITEM
WHERE	PRICE > ANY (SELECT PRICE FROM ITEM WHERE CATEGORY = 'GME')	

--OUTER JOIN
SELECT	R.REP_NUM, R.LAST_NAME, C.CUSTOMER_NAME
FROM	REP R INNER JOIN CUSTOMER C ON R.REP_NUM = C.REP_NUM
ORDER BY R.LAST_NAME, C.CUSTOMER_NAME


SELECT	R.REP_NUM, R.LAST_NAME, C.CUSTOMER_NAME
FROM	REP R LEFT OUTER JOIN CUSTOMER C ON R.REP_NUM = C.REP_NUM
ORDER BY R.LAST_NAME, C.CUSTOMER_NAME
		