CREATE PROCEDURE INSERTITEM
--ADD THE PARAMETERS FOR THE STORE PROCEDURE HERE 
	@ITEM_NUM CHAR(4),
	@DESCRIPTION CHAR(30),
	@CATEGORY CHAR(3),
	@ON_HAND INT,
	@STOREHOUSE CHAR(1)=NULL
AS
BEGIN
	DECLARE @COUNT INT

    -- Insert statements for procedure here
	SELECT @COUNT=COUNT(*) FROM ITEM WHERE ITEM_NUM=@ITEM_NUM
	IF(@COUNT=0)
BEGIN 
	INSERT INTO ITEM 
	(ITEM_NUM,DESCRIPTION,CATEGORY,ON_HAND,STOREHOUSE)
	VALUES(@ITEM_NUM,@DESCRIPTION,@CATEGORY,@ON_HAND,@STOREHOUSE)
END
ELSE 
BEGIN 
	PRINT 'ITEM' + @ITEM_NUM + 'ALREADY EXIST IN DB'
	END
END
GO
